# Generated by Django 4.2.3 on 2023-07-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyerid', models.IntegerField(db_column='BuyerID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'buyer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.IntegerField(db_column='CustID', primary_key=True, serialize=False)),
                ('custname', models.CharField(db_column='CustName', max_length=45)),
                ('custcontact', models.IntegerField(db_column='CustContact')),
                ('custcity', models.CharField(db_column='CustCity', max_length=20)),
                ('custhouse', models.CharField(blank=True, db_column='CustHouse', max_length=45, null=True)),
                ('custdob', models.DateField(db_column='CustDOB')),
                ('custemail', models.CharField(db_column='CustEmail', max_length=30)),
                ('custgender', models.CharField(db_column='CustGender', max_length=1)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(db_column='EmpID', primary_key=True, serialize=False)),
                ('empname', models.CharField(db_column='EmpName', max_length=45)),
                ('empemail', models.CharField(db_column='EmpEmail', max_length=30)),
                ('empgender', models.CharField(db_column='EmpGender', max_length=1)),
                ('empcity', models.CharField(db_column='EmpCity', max_length=20)),
                ('emphouseno', models.CharField(db_column='EmpHouseNo', max_length=45)),
                ('empdob', models.DateField(db_column='EmpDOB')),
            ],
            options={
                'db_table': 'employee',
                'db_table_comment': '\t\t\t\t\t\t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventid', models.IntegerField(db_column='InventID', primary_key=True, serialize=False)),
                ('availability', models.CharField(blank=True, db_column='Availability', max_length=255, null=True)),
                ('noofvehicles', models.IntegerField(blank=True, db_column='NoOfVehicles', null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('mgrid', models.IntegerField(db_column='MgrID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manid', models.IntegerField(db_column='ManID', primary_key=True, serialize=False)),
                ('manname', models.CharField(blank=True, db_column='ManName', max_length=255, null=True)),
                ('mancity', models.CharField(blank=True, db_column='ManCity', max_length=255, null=True)),
                ('mancontact', models.CharField(blank=True, db_column='ManContact', max_length=255, null=True)),
                ('manemail', models.CharField(blank=True, db_column='ManEmail', max_length=255, null=True)),
            ],
            options={
                'db_table': 'manufacturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payid', models.IntegerField(db_column='PayID', primary_key=True, serialize=False)),
                ('dateofpayment', models.DateField(blank=True, db_column='DateOfPayment', null=True)),
                ('paymentmethod', models.CharField(blank=True, db_column='PaymentMethod', max_length=255, null=True)),
                ('paymentstatus', models.CharField(blank=True, db_column='PaymentStatus', max_length=255, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('renterid', models.IntegerField(db_column='RenterID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'renter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('spid', models.IntegerField(db_column='SPID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'salesperson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicerecord',
            fields=[
                ('service_id', models.IntegerField(db_column='Service_ID', primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('servicetype', models.CharField(blank=True, db_column='ServiceType', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, db_column='Cost', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'servicerecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supid', models.IntegerField(db_column='SupID', primary_key=True, serialize=False)),
                ('supname', models.CharField(blank=True, db_column='SupName', max_length=255, null=True)),
                ('supcity', models.CharField(blank=True, db_column='SupCity', max_length=255, null=True)),
                ('supcountry', models.CharField(blank=True, db_column='SupCountry', max_length=255, null=True)),
                ('supcontact', models.CharField(blank=True, db_column='SupContact', max_length=255, null=True)),
                ('supemail', models.CharField(blank=True, db_column='SupEmail', max_length=255, null=True)),
                ('sparepartname', models.CharField(blank=True, db_column='SparePartName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('techid', models.IntegerField(db_column='TechID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'technician',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleid', models.IntegerField(db_column='VehicleID', primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=10, null=True)),
                ('vin', models.CharField(blank=True, db_column='VIN', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('mileage', models.IntegerField(blank=True, db_column='Mileage', null=True)),
                ('fueltype', models.CharField(blank=True, db_column='FuelType', max_length=255, null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
    ]
